### ISSUE TITLE
v891 vs v5: actions don't work

### ISSUE THREAD

**Issue by mmazur** [mgsloan/todoist-shortcuts#1]
Chrome 64, todoist v891, latest chrome extension shortcuts. Navigation does work, though things like "done", sorting, archiving and a few others don't. Extension does complain it's been tested against todoist 890 and not 891, so hopefully that's the problem.

**Comment by mmazur** [comment]
Ok, just ran a full set of tests with language set to en. Here's what doesn't work:
- sorting of any kind, but judging by the source code, that's just a matter of docs getting ahead of themselves: it's not implemented (yet)
- 'done' and 'archive' for unselected items

To expand on the last point: 'x' + 'd'/'e' works. 'd'/'e' without the earlier explicit selection does not.

**Comment by mgsloan** [comment]
@mmazur Thanks for looking into it!  I've pushed https://github.com/mgsloan/todoist-shortcuts/commit/a3848af8537ba82ac6de724859fdbac17b576b80 which fixes it.  It was actually intentional that `d` and `e` didn't work, but wasn't properly documented.  The idea was that you don't want to accidentally do these operations, so it emulated gmail's UI.  In my own usage, though, I have it set to allow them on the cursor.

To make it consistent with the docs, I made the default be that you can use `d` and `e` on normal items.

**Comment by mgsloan** [comment]
@mmazur If you are interested in trying it out before the release, or making other changes, I've documented it here https://github.com/mgsloan/todoist-shortcuts#how-to-customize-keyboard-shortcuts .  Keen on merging PRs, because I won't have time to make it perfect.

**Comment by mmazur** [comment]
Yup, just found WHAT_CURSOR_APPLIES_TO and switched it. Yes, in my opinion as well it should be 'all' bey default. This extension isn't for the faint of heart.

**Comment by mmazur** [comment]
I've switched to using tampermonkey for running this already. Will ping you with a few PRs within the next few days.

**Comment by mgsloan** [comment]
Awesome, I look forward to it!

Yes, this was initially developed as a tampermonkey script and then turned into an extension for easier distribution / security.
