### ISSUE TITLE
<bug> Keyboard Shortcuts don't work after using the 'v' keyboard shortcut. The focus change to the browser window

### ISSUE THREAD

**Issue by idonimni** [mgsloan/todoist-shortcuts#103]

**Comment by mgsloan** [comment]
Hmm, I can't reproduce this bug.  Does it still occur for you?  Perhaps it is an interaction with some other extension?

**Comment by idonimni** [comment]
Yes, it still occurs to me. I don't know about other extensions causing
that.

**Comment by mgsloan** [comment]
Curious!  One thing I just noticed is that the chrome extension is stuck on version 69.  I needed to add some privacy descriptions to get the extension reviewed, and version 71 is currently in review.

My changes since then did not address a bug like this, but they did improve some keymap behavior, so perhaps that also resolved this problem.

**Comment by idonimni** [comment]
I hope so. I'm using your extension a lot so if that will be solved, it
will improve my productivity dramatically.

Does the extension auto-update or do I need to somehow know when the new
version released and update it manually?

**Comment by mgsloan** [comment]
I believe it should auto update, looks like version 71 is now up
