### ISSUE TITLE
Button/shortcut to save current URL to Todoist task

### ISSUE THREAD

**Issue by kellyarwine** [mgsloan/todoist-shortcuts#116]
Suggestion:  I'm looking for a way to easily save websites to Todoist.  My current method is pull up website, click URL, cmd+C, click on Todoist tab in brower, type "a", paste.  Blah.  That's a lot of steps and I save a lot of websites.

There are 2 chrome extensions for this flow but neither work.  I was trying to find something like [this](https://chrome.google.com/webstore/detail/send-to-trello/phkdhbnamindiecpekhmmagjhchphlmh?hl=en) but for Todoist.  What would be great is if, when viewing a website, a bookmark button or shortcut key press would save the website to Todoist.  It could just save to Inbox with no date or today's date - at least for an initial pass.

Would easily pay 5 coffees for this.  ;)

**Comment by mgsloan** [comment]
Great idea!

I would like to have this to, so I might get around to doing it.  I tried to reuse code from the "Todoist for Chrome" extension, but it turns out that it makes privileged web requests that only that extension can make.  When my extension makes the same request, it is not authorized.

I think I know a decent way to do this, but it will only work if a todoist tab is open.

**Comment by kellyarwine** [comment]
You saved me some time.  I was going to look into doing it too since it was so important to me (30% of my tasks are links to read, emails, etc.).

**Comment by mgsloan** [comment]
You're welcome!

The "Todoist for Chrome" extension might still be helpful to you, because
it does support adding URLs as tasks.  The only issue with it is that it is
not accessible via a keyboard shortcut, but instead a right click context
menu.  You right click on the page and then click the "Add to Todoist" or
something like that, and the page will be added as a task.  If you select
text, it will even incorporate that text in the task.

**Comment by kellyarwine** [comment]
THAT is awesome!  I had no idea that was a thing.  I can just do that (use the extension).  Would love a shortcut but, for now, this is great!

**Comment by mgsloan** [comment]
Yeah, it's a nice extension!  Maybe they will accept a patch adding
keyboard support for that action

**Comment by mgsloan** [comment]
Closing as wontfix, since this is handled by the Todoist for Chrome extension.
