### ISSUE TITLE
toggl integration - stop and start timer (also in task view)

### ISSUE THREAD

**Issue by mrderiuzz** [mgsloan/todoist-shortcuts#118]
1. shift+c starts toggl timetracking but it doesn't seem to work in task view (i.e. after clicking 'i' on a given task in task list view). Can we make it work also in that view?

2. shift+c doesn't seem to be stopping the timer. Could we change it so that shift+c actually flips the state of the button (click if it's stopped, stop it when it's running)?

**Comment by mgsloan** [comment]
Hey, thanks for bringing my attention to this!

For me `shift+c` does stop the timer, but only if the current task selection has the timer in it.  I suppose it could click an active timer button if visible.  However, that seems inconsistent to me for the case where you view a project that doesn't have the active item in it.  In that case, `shift+c` would instead activate a timer rather than toggling the timer state.

I believe this is probably confounded by the toggl button(s) usually being invisible - #119

I think I've fixed it working in the task view in the work on #114

**Comment by mgsloan** [comment]
I've just released version 77, has the task view fix
