### ISSUE TITLE
Bug: Operations on multiple selected tasks no longer work

### ISSUE THREAD

**Issue by GraphicThinkPad** [mgsloan/todoist-shortcuts#129]
If you select two tasks with x and then try to assign them both to a project via `v`, nothing happens. In the past, this was not the case.

Edit: This appears to be the case with any operation that acts on multiple selected tasks.

**Comment by GaryFurash** [comment]
Yes same issue w/ # (delete)

**Comment by mgsloan** [comment]
It seems like something shifted in Todoist frontend development where disambiguating classes are being removed from buttons.  My guess is that things are being refactored atop a new frontend framework, or something, such that the appearance is the same but the DOM is very different. I have contacted Doist about it, and they are keen to add some disambiguating attributes so that todoist-shortcuts can work properly for non-english localizations.

In the meantime, since core functionality is broken, I am working on a workaround which matches on the displayed text, and so will only work for the english localization.

**Comment by mgsloan** [comment]
English-only workaround released in version 83
