### ISSUE TITLE
Reassigning existing keyboard shortcuts (sorting)

### ISSUE THREAD

**Issue by mmazur** [mgsloan/todoist-shortcuts#13]
Considering there's going to be a lot of features to handle and this might potentially get shipped with base todoist, I was wondering whether it's be allowed/doable to take back the s/p/r sorting shortcuts. I'd much prefer them to work the same way 'move to project' or 'navigate project' works, meaning a two-key combo. So 's' would 'open' the sort menu and then you could pick d/p/n/r for date/priority/name/responsible (or maybe use left-hand only keys, that'd be even faster).

Two question wrt to that:

1. @mgsloan you dove deep into browser keyboard support: is it possible for todoist-shortcuts to reliably intercept keys heading for todoist and doing something else with them/ignoring them?
2. @amix (dunno if you'll get the notification and see this, but worth a shot): would you be ok with a tiny portion of todoist's already-existing shortcuts being changed to something else?

**Comment by mgsloan** [comment]
@mmazur Yes, that all makes sense to me.  Currently todoist-shortcuts does actually intercept all keys.  For original todoist shortcuts like u/s/p/r, they need to be listed in order to work.  It is probably missing some original shortcuts that should still work.

I like involving opening the sub-menu because then potentially the UI can be directly annotated with the keybinding to hit, similarly to how the `g` key works.

**Comment by amix** [comment]
> would you be ok with a tiny portion of todoist's already-existing shortcuts being changed to something else?

It would be best if we stayed compatible. The reason is that some of these keys have been used for 8+ years, people will get very pissed if we remap them :)

**Comment by mgsloan** [comment]
Yep, I'm in favor of keeping them the same where possible.  Down the road if it becomes an issue it can be a non-default option.
