### ISSUE TITLE
Shortcuts for priority not working in upcomming section

### ISSUE THREAD

**Issue by aiv** [mgsloan/todoist-shortcuts#133]
Shorts for priority (1,2,3,4,5) after "upcoming" section update, stopped working.
On keyPress, todoist is showing context menu for a task.

**Comment by mgsloan** [comment]
Thanks for reporting!

The new additions to the UI do not have attributes that allow disambiguation.  Even though the menu looks the same, I bet it's entirely new code rendering it.  I've been in touch with some folks at Doist and my understanding is that they will add some disambiguating attributes so that this can be fixed.

This issue is tracked by https://github.com/mgsloan/todoist-shortcuts/issues/110
