### ISSUE TITLE
Safari extension

### ISSUE THREAD

**Issue by rakleed** [mgsloan/todoist-shortcuts#161]
It would be nice if you made a Safari extension. Since starting with version 14, support for the WebExtensions API has appeared. More details: https://developer.apple.com/documentation/safariservices/safari_web_extensions

**Comment by mgsloan** [comment]
This is a good idea, but unfortunately I do not have a mac / xcode.  I'd
certainly appreciate it if someone would repackage it for Safari, please do
let me know if you're interested.

**Comment by codeluggage** [comment]
Hey - I gave this a quick try and have some more details in case anyone would like to make it work. I found a different way to accomplish what I needed so I'm not spending any more time on making this work in Safari, but hopefully this can be useful to someone else giving this a try. 

_tldr; It converts to a Safari extension easily with 1 command. The import of dependencies does not work out of the box._ 

In order to get started with this you'll need XCode installed. With that, you get an executable called `safari-web-extension-converter`.

The steps I went through were: 

1. Make sure XCode is installed and `xcrun safari-web-extension-converter` is possible to run
2. Clone this repo
3. Run the following command:

```
xcrun safari-web-extension-converter todoist-shortcuts/src --project-location todoist-shortcuts-safari --app-name todoist-shortcuts --bundle-identifier com.mgsloan.todoist-shortcuts --swift --copy-resources
```

The folder I ran this from is the folder containing this repo. I pointed it at `todoist-shortcuts/src`, or if you're inside of this repo's folder, it would be just `src`.

A few notes on my choices here, because they're all guesses:
`--project-location`:  Doesn't matter, I just gave it `-safari` as a name. This is where the XCode project will land.
`--app-name`: Don't think it matters.
`--bundle-identifier`: Don't think it matters.
`--swift`: Probably more support and help for this these days that good old Objective-C.
`--copy-resources`: I assume it will link to the original directory otherwise. This may be better to skip when debugging this so you can move files around to try to make it work.

4. Build the XCode project created
5. Open Safari
6. Make sure you have access to the Developer menu (in Safari preferences)
7. Go to Todoist in Safari, where you'd want to use the extension to interact with your tasks
8. Click the menu item "Allow unsigned extensions" - this seems to reset either per tab or for each restart of Safari
9. Find the resources built from your XCode project and double click the todoist-shortcuts app (red icon)
10. Click the "Quit" choice in the dialog to go to Safari
11. In the list of extensions in Safari, you should now see the newly built extension. If you don't see it, check some of the steps above as you may not have allowed unsigned extensions.
12. Open the inspector/console on the Todoist page
13. Try to use a vim shortcut. Notice that there is some attempt at highlighting at the bottom of the page, but it fails.


The issue is very likely that the dependencies (like mousetrap) is not included in the build. This likely has to do with how only `src` was included in the conversion of the extension. 

Here are my console logs from Safari when running the extension: 

```
[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' appears in neither the script-src directive nor the default-src directive of the Content Security Policy. (app, line 0)
[Info] Content blocker prevented frame displaying https://todoist.com/app/#project%1234 from loading a resource from https://www.google-analytics.com/analytics.js (app, line 14)
[Info] Content blocker prevented frame displaying https://todoist.com/app/#project%1234 from loading a resource from https://www.google-analytics.com/analytics.js
[Log] Sending latency from page_performance – "0.56" – "todoist.com/app" (page_performance.js, line 38)
[Error] Failed to load resource: the server responded with a status of 404 () (csp_report, line 0)
[Error] todoist-shortcuts: – "Failed to figure out background color:" (3)
TypeError: background.computedStyleMap is not a function. (In 'background.computedStyleMap()', 'background.computedStyleMap' is undefined)
"getStack@safari-web-extension://1C3D4D72-0BD5-4DAD-B59D-C629EF552F4F/todoist-shortcuts.js:3559:22
error@safari-web-extension://1C3D4D72-0BD5-4DAD-B59D-C629EF552F4F/todoist-shortcuts.js:3550:23
safari-web-extension://1C3D4D72-0BD5-4DAD-B59D-C629EF552F4F/todoist-shortcuts.js:4056:14
withId@safari-web-extension://1C3D4D72-0BD5-4DAD-B59D-C629EF552F4F/todoist-shortcuts.js:3642:15
updateBackgroundColor@safari-web-extension://1C3D4D72-0BD5-4DAD-B59D-C629EF552F4F/todoist-shortcuts.js:4043:11
global code@safari-web-extension://1C3D4D72-0BD5-4DAD-B59D-C629EF552F4F/todoist-shortcuts.js:4060:24"
"Consider reporting this as an issue to http://github.com/mgsloan/todoist-shortcuts"
	(anonymous function) (vendor.ae1ffbd728ad8c94913d.js:1:277615)
	error (todoist-shortcuts.js:3553)
	(anonymous function) (todoist-shortcuts.js:4056)
	withId (todoist-shortcuts.js:3642)
	updateBackgroundColor (todoist-shortcuts.js:4043)
	Global Code (todoist-shortcuts.js:4060)
[Log] todoist-shortcuts: – "Found #content div - initializing todoist-shortcuts!" – "(this is fine)" (vendor.ae1ffbd728ad8c94913d.js, line 1)
[Error] ReferenceError: Can't find variable: mousetrap
	updateKeymap (todoist-shortcuts.js:1805)
	handlePageChange (todoist-shortcuts.js:1671)
	initialize (todoist-shortcuts.js:4492)
	initializeWhenContentAppears (todoist-shortcuts.js:4550)
	Global Code (todoist-shortcuts.js:4554)
[Error] todoist-shortcuts: – "Failed to figure out background color:" (3)
TypeError: background.computedStyleMap is not a function. (In 'background.computedStyleMap()', 'background.computedStyleMap' is undefined)
"getStack@safari-web-extension://1C3D4D72-0BD5-4DAD-B59D-C629EF552F4F/todoist-shortcuts.js:3559:22
error@safari-web-extension://1C3D4D72-0BD5-4DAD-B59D-C629EF552F4F/todoist-shortcuts.js:3550:23
safari-web-extension://1C3D4D72-0BD5-4DAD-B59D-C629EF552F4F/todoist-shortcuts.js:4056:14
withId@safari-web-extension://1C3D4D72-0BD5-4DAD-B59D-C629EF552F4F/todoist-shortcuts.js:3642:15
updateBackgroundColor@safari-web-extension://1C3D4D72-0BD5-4DAD-B59D-C629EF552F4F/todoist-shortcuts.js:4043:11
i@https://d3ptyyxy2at9ui.cloudfront.net/assets/vendor.ae1ffbd728ad8c94913d.js:90:7625"
"Consider reporting this as an issue to http://github.com/mgsloan/todoist-shortcuts"
	(anonymous function) (vendor.ae1ffbd728ad8c94913d.js:1:277615)
	error (todoist-shortcuts.js:3553)
	(anonymous function) (todoist-shortcuts.js:4056)
	withId (todoist-shortcuts.js:3642)
	updateBackgroundColor (todoist-shortcuts.js:4043)
	i (vendor.ae1ffbd728ad8c94913d.js:90:7626)
[Error] ReferenceError: Can't find variable: mousetrap
	updateKeymap (todoist-shortcuts.js:1805)
	handlePageChange (todoist-shortcuts.js:1671)
[Error] ReferenceError: Can't find variable: initializing
	(anonymous function) (todoist-shortcuts.js:1729)
[Error] ReferenceError: Can't find variable: mousetrap
	updateKeymap (todoist-shortcuts.js:1805)
	handleBodyChange (todoist-shortcuts.js:1766)
[Error] ReferenceError: Can't find variable: initializing
	(anonymous function) (todoist-shortcuts.js:1729)
[Error] WebSocket connection to 'wss://ws.todoist.com/ws?token=123456' failed: Unexpected response code: 504
```

**Comment by mgsloan** [comment]
Awesome, thanks for giving this a try!

> The issue is very likely that the dependencies (like mousetrap) is not
included in the build. This likely has to do with how only src was included
in the conversion of the extension.

That isn't the issue, everything is in src/todoist-shortcuts.js.  It
includes a minified copy of the mousetrap library.

The errors are referring to variables that are declared within the top
level { } block which contains the code those errors are being thrown
from.  I have no idea why these errors would occur, the variables should be
in scope.

  * declaration of `mousetrap` variable
https://github.com/mgsloan/todoist-shortcuts/blob/d7c8b6dcc604934cd56bdd4cfffb4774469cbfca/src/todoist-shortcuts.js#L340
  * declartion of `initializing` variable
https://github.com/mgsloan/todoist-shortcuts/blob/d7c8b6dcc604934cd56bdd4cfffb4774469cbfca/src/todoist-shortcuts.js#L4489

**Comment by zemackdaddy** [comment]
I don't know jack about JS.  I removed the surrounding {} and built the safari web extension and it actually lets me navigate up and down, select tasks, and do many other things, but other JS errors appear in the console.  Probably because of what I did.

But it certainly seems that Safari doesn't agree with the scope?

**Comment by mgsloan** [comment]
Interesting!  I've replaced the bare use of

```
{
    ...
}
```

With

```
(function() {
    ...
})();
```

Which should behave identically but be a little more typical.  I don't have convenient access to Safari to debug it further.

**Comment by f4jNZgfgG9oDqmvcNvUF** [comment]
@mgsloan That actually seems to work very well.  I see some console errors like "Failed to figure out background color" and "Couldn't find ID – page_background" but those don't seem to affect functionality as far as I can tell.  I thought I saw a reference error, but cannot duplicate it.  Then again, whenever I open the javascript console on any given page I can often see an error :)

**Comment by mgsloan** [comment]
That's awesome that the fix worked!  The "Failed to figure out
background color" errors are benign.  The most recent code changes them to
warnings instead.

**Comment by rakleed** [comment]
@mgsloan why did you close the issue?

**Comment by mgsloan** [comment]
Since it sounds like there is a viable approach to using the extension in safari.

I don't have any way of packaging a safari extension or testing with safari, and so there is no further action for me to take.  Also, I like to release frequently and adding more to that process would add friction.

Feel free to put up a safari version of the extension

**Comment by champagnealexandre** [comment]
Late to the party but found this thread while googling for the same issue (Safari extension).

I was able to build the Safari extension but for some reason allowing unsigned extensions in Sonoma makes my Safari crash. I  then tried signing it, but found out that extensions can’t be used with the new Sonoma standalone Safari apps feature.

Final solution: use any way to inject jscript into the page (such as the Cascada safari extension) and just copy-paste the content of ```mousetrap.js``` followed by that of ```todoist-shortcuts```. This way there’s no need to rebuild the whole Safari extension every time the script gets updated. Personally I use a webkit-based solution to make web apps local (Fluid) which allows to use javascript userscripts out of the box (see #260), works beautifully to have a standalone safari-based app which has todoist-shortcuts enabled.
