### ISSUE TITLE
moving todo's across sections via shift+arrow 

### ISSUE THREAD

**Issue by Christian-Klaperek** [mgsloan/todoist-shortcuts#166]
Hi Michael !  Christian here. 

The issue I found is shown in the attached screen capture.

The todo "A", is moved using shift+arrow, from top to bottom. 
It passes thru two sections (Section X and Y). Next it is moved 
back up to the top. "C" and "D" are also moved from Sections 
X and Y to the top. Everything works fine. 
 
Next, when trying to move A back down again into Sections X 
and Y, it won't go. It won't go back into Section X. The other 
todos (B, C and D) also have the same issue.

I cant tell if this is by design, or an issue that could be solved ...  

Cheers
Christian

https://user-images.githubusercontent.com/50895699/103449228-f3638f80-4cd7-11eb-8d60-98b6fbd1e2b1.mp4

**Comment by mgsloan** [comment]
Hey, thanks for the report.  I haven't tried your exact repro steps, but I did make it so that tasks can be dragged into empty sections, and attempted to make it so they don't skip over sections.  Version 121 includes those changes.  Please let me know if that fixes the problem!

Unfortunately, todoist's drag and drop behavior is pretty fiddly / unpredictable.  It's sufficient for humans since you can see where the drag and drop will go, but I haven't put in the effort to emulate the human's behavior of "wiggle the task around until the drop target is right".

**Comment by Christian-Klaperek** [comment]
Hi Michael 

Thanks for responding so fast! 
I gave it a try and yes tasks can now be dragged into empty sections.
But I think it still skips over sections. ( I made a screen capture again).
I'm using version 123. 
Christian

https://user-images.githubusercontent.com/50895699/103621868-7438ba80-4f68-11eb-9452-ce0738d461ba.mp4


](url)

**Comment by mgsloan** [comment]
Closing as wontfix.  I appreciate the detailed report, but I don't think I'll be working on this, drag-n-drop movement is one of the fiddliest parts of the extension.
