### ISSUE TITLE
* h collapse all tasks not working

### ISSUE THREAD

**Issue by albert239825** [mgsloan/todoist-shortcuts#167]
Hey Michael,

Sorry to bother you again. Thank you so much for the help last time. For some reason, * h for collapsing all tasks is not working for me but * l for expanding tasks is. Thank you so much and enjoy the rest of your day.

**Comment by mgsloan** [comment]
Hmm, curious!  For some reason `h` keypresses aren't being handled correctly.  I'm guessing it has something to do with #132.  I looked into it a bit, but didn't readily figure it out.

In the meantime, I've made it so that `* left-arrow` and `* right-arrow` also work for expanding / collapsing all tasks, in version 123

**Comment by changpowpow** [comment]
Are there any updates on this?

**Comment by mgsloan** [comment]
No updates.  This is pretty low on my priority list.

**Comment by mgsloan** [comment]
I've updated the docs to reflect that `* h` does not work.

**Comment by mgsloan** [comment]
As a result of the fix to #184 this is now fixed too!
