### ISSUE TITLE
Navigate subtasks in Open Task View

### ISSUE THREAD

**Issue by jamesx4** [mgsloan/todoist-shortcuts#188]
It would be nice if one could navigate the subtasks using the 'J' and 'K' keys to move up or down over the subtasks when in the Open Task View, 'i'.  As is I can almost keep my hands on the keyboard except when I need to do something with an existing subtask.

**Comment by mgsloan** [comment]
Good idea!  My work on todoist-shortcuts is mostly in maintenance mode, though (maintaining existing features).  Would merge a PR adding this, though.

In the meantime there are some alternative ways of doing this:

1. If the task is collapsed, `l` re-expands it, can use `j` to select the subtasks
2. If in a label / some other view that doesn't show subtasks, can use `shift+g` to view the task in the project, so that the subtask are visible

**Comment by jamesx4** [comment]
Thanks for the alternatives!  Those actually work really well.  Man, you
know your shortcuts!!

-Kevin
