### ISSUE TITLE
Bulk edit mode?

### ISSUE THREAD

**Issue by error9900** [mgsloan/todoist-shortcuts#203]
Obvious example is processing tasks in the Inbox:

1. View Inbox
2. `* i` to initiate "bulk edit" mode
3. Top task in Inbox pops open in side panel view (like the `i` shortcut currently does) for editing of multiple attributes at once, e.g. schedule, project, and priority
4. `escape` to close side panel view
5. Next task at top of Inbox automatically pops open in side panel view.
6. Rinse and repeat until no more tasks in Inbox

This could obviously work for any view, and not just the Inbox.

**Comment by mgsloan** [comment]
It's a good idea!  However, Version 147 removes special handling of task view, and instead uses Todoist native shortcuts for this.  This is due to the redesigned task view being quite different (see #204 for discussion).

With the native shortcuts, you can use `j` and `k` within the task view, which I think nicely accomplishes what you describe here.

**Comment by error9900** [comment]
Hmm. So the functionality I was thinking of would work fine with Todoist native shortcuts within the task view...

I was mainly trying to mimic the automated workflow you have for `Bulk reschedule mode` and `Bulk move mode`...

Would it not be possible to do something similar while relying on native shortcuts within the task view?, i.e.

1. Bulk edit mode activated
2. Extension opens top task in task view
3. User makes changes using native shortcuts, including changes that move the task from the current view.
4. User closes task view.
5. Extension detects task view closed (or list view active again) (or maybe detect Esc key closing task view).
6. Extension opens the new top task in task view.
7. Rinse and repeat steps 3 through 6 until all tasks have been moved from current view/list.

**Comment by mgsloan** [comment]
True, could do!  Feel free to open a PR adding this.  I do not plan to implement it though, because:

* I don't use the task view
* There are currently two versions of the task view
* The new version of the task view has this functionality in the form of native `j`/`k` bindings that navigate to next / previous tasks focused in the task view.
