### ISSUE TITLE
New task view (experimental feature) doesn't work with todoist-shortcuts

### ISSUE THREAD

**Issue by Qu3cus** [mgsloan/todoist-shortcuts#204]
This is just a heads up that the extension currently doesn't work with the task view that Todoist is testing as an experimental feature at the moment. Everything I've tested works just fine in the main interface, whether or not the new task view option is checked, it just doesn't work in the experimental task view itself.

Obviously I wouldn't expect compatibility with an unfinished feature, and chasing around trying to integrate with a feature that isn't yet complete would be a futile exercise, so this is more of an advance warning of a compatibility-breaking update that might be coming down the line at some point.

**Comment by mgsloan** [comment]
Thanks for letting me know!  Is the experimental task view visible on
beta.todoist.com?

**Comment by Qu3cus** [comment]
Sorry - never saw the notification for this reply - from beta.todoist.com you need to go to the "advanced" pane in the settings, check "experimental features", then check "new task view"

**Comment by Qu3cus** [comment]
According to a knowledge base article from todoist you might have to update after enabling experimental features to see the features available to test. It also looks like "experimental features" has replaced the beta programme, so I imagine beta.todoist.com doesn't do anything additional any more (I hadn't realised this myself). 

https://todoist.com/help/articles/how-to-test-experimental-features

**Comment by mgsloan** [comment]
Ah, interesting, thanks!  I think somehow I was on beta.todoist.com and the
new task view toggle wasn't in the settings there.  I do see it on the main
todoist.com

**Comment by mgsloan** [comment]
The new DOM has obfuscated class names so it would be challenging to bind keyboard shortcuts to it.  As such, I'm deleting the special handling of task view, and instead falling back on native Todoist keyboard shortcuts for the task view.

**Comment by error9900** [comment]
This change is a little rough...

Now we've got a situation where Shift + T is `schedule by editing text` in the list view, but `Remove due date` in task view...so it's now very easy to accidentally remove a due date in task view...

Might make more sense to just scrap scheduling from the extension altogether rather than trying to memorize and work with different, conflicting shortcuts, based on your view...

**Comment by mgsloan** [comment]
Makes sense!  I forgot that the old task view still exists (I was used to the beta.todoist.com url instead of the new experimental toggle in settings).

I've brought back the old keybindings in the meantime, and it now uses the native shortcuts for the experimental task view.

Hopefully by the time the new task view becomes default it will be more viable to bind shortcuts to it.

**Comment by mgsloan** [comment]
I've fixed this in version 149!  Some keybindings will only work in the english translation, unfortunately.

**Comment by mdbraber** [comment]
With Experimental Features turned on in v2953 the priority shortcuts are broken (because of different class names). Is this also the case for other users? I've switched off Experimental Features for now.

**Comment by fabiocpn** [comment]
> With Experimental Features turned on in v2953 the priority shortcuts are broken (because of different class names). Is this also the case for other users? I've switched off Experimental Features for now.
I can confirm. "Experimental features" is breaking the shortcut to change priorities.

**Comment by mgsloan** [comment]
Thanks for reporting!  Happily the fix is simple.  I opened #233 to track it.
