### ISSUE TITLE
Add subtask directly from task list

### ISSUE THREAD

**Issue by mdbraber** [mgsloan/todoist-shortcuts#210]
When viewing the list of tasks I can do the following to add a subtask

- Press `i` to open task view and `a` to add a sub task
- Press `a` to add a regular task and then press  `shift-l` to indent the task

Is there a way to directly add a subtask to a selected task (without opening task view)?

**Comment by masonc15** [comment]
I would also use this a ton if possible.  +1

**Comment by mgsloan** [comment]
A single keyboard shortcut for this would be quite tricky to add!  Here are some suggestions about existing shortcuts for this:

I don't think there is a way to do this directly in agenda / label / filter views just due to how Todoist's UI works.  If you do want to work inline though, you can use `shift-g` to focus the task in its project.

Sidenote: `shift-g` has a bug that will be fixed in version 150, early versions do not select the right task after navigation (this used to work, not sure when it broke)

> Press `a` to add a regular task and then press `shift-l` to indent the task

It's more direct to use `o` to add a regular task below the currently focused task. (`a` adds to the end)
