### ISSUE TITLE
Shortcut "v" loses task focus after moving a selected task to a section of the same project

### ISSUE THREAD

**Issue by antois** [mgsloan/todoist-shortcuts#216]
How to reproduce:

1. Go to any project (e.g. Inbox)
2. Focus on any task in the project (with the blue vertical bar)
3. Hit "v" and select a section of the same project to send the task to 
4. Notice that the blue vertical bar has disappeared from the page and it requires a page reload to bring it back

FYI the task focus works as expected if moving a task to another project, instead of another section in the same project.

**Comment by mgsloan** [comment]
Thanks for reporting!  Fixed in version 159.

Unfortunately having some issues with getting things updated in the chrome webstore, as I'd uploaded some prior zips with missing files, which were rightfully rejected.  Version 157 is still pending review, so I can't upload 159 yet.  So for now stuck on version 152 in chrome webstore
