### ISSUE TITLE
Stopped working completely!

### ISSUE THREAD

**Issue by shansell** [mgsloan/todoist-shortcuts#254]
Hi. 
The Todoist Shortcuts extension has completely stopped working for me. 
I'm on a Mac, upgraded to Sonoma. I've tried it in Chrome and Edge over several days. None of the shortcuts work. Do others have this problem? What can I do?

Help. This extension is what makes Todoist workable for me.
Thanks
Saul

**Comment by ErikOsterud** [comment]
Are you using Todoist's **_New Layout (Beta)_**?

**Comment by shansell** [comment]
I don't think so, but I'm not sure. How can I check?

**Comment by shansell** [comment]
So I went to the Todoist settings and turned off "use experimental features." That seems to have solved the problem. Whew.
I hope that doesn't mean that some future update will kill this extension.

**Comment by ErikOsterud** [comment]
It'll show in your settings menu when experimental features are enabled:
![image](https://github.com/mgsloan/todoist-shortcuts/assets/740128/5a1c9242-8d76-45fc-84cb-2fa86730a5fd)

Todoist Shortcuts in Chrome/Edge are working for me in the current layout, but not in the New Layout. I assume the New Layout breaks lots of things since Todoist will be changing so much :)

**Comment by mgsloan** [comment]
Total breakage is pretty bad and seems likely these changes will be made default sometime soonish, so I put a couple hours into fixing.

**Comment by mgsloan** [comment]
On first pass missed that `q` for quick add is broken in the new design.  Unfortunately I can't upload version 182 with the fix until 181 is done with review.
