### ISSUE TITLE
Add task "Q" does not work (was issue 266, but that one is closed)

### ISSUE THREAD

**Issue by EelkoL** [mgsloan/todoist-shortcuts#270]
The Q key does not add a task. I added log output in the comments of issue 266.

**Comment by holstuwe** [comment]
Copy that. Latest firefox on windows.

**Comment by mgsloan** [comment]
Is this still occurring?  I don't have the issue with firefox on linux.  It'd be very surprising to me if linux vs windows mattered here.

**Comment by EelkoL** [comment]
Yes, this is still occuring. 
Other extensions work fine, I use lastpass, diigo, deepl translator, clip to onenote, application launcher for drive (google) and some others. 
Chrome version is:
Chrome is up-to-date
Versie 122.0.6261.112 (Officiële build) (64-bits)

**Comment by holstuwe** [comment]
@EelkoL  @mgsloan Can no longer confirm this behaviour. Firefox on Windows 11 (123.0.1 (64-Bit)), Extension version 195. "q" is adding tasks without any problem. Other shortcuts like "j", "k"... are working fine as well.

**Comment by mgsloan** [comment]
@EelkoL Ahh, I have a theory.  I noticed that your logs have `(anoniem)` and so you are probably using Todoist with Dutch locale.  Unfortunately the fix for #266 was to match the button based on the text.  Todoist used to have fairly semantic names for buttons to use, but increasingly only has obfuscated class names:

![image](https://github.com/mgsloan/todoist-shortcuts/assets/22570/99bc6fcd-8103-455c-a19d-66b693464b7e)

So, unfortunately the solution is to switch to the english locale or make a modified version that knows about the dutch localization https://github.com/mgsloan/todoist-shortcuts?tab=readme-ov-file#how-to-customize-keyboard-shortcuts .  In the meantime I'd also be happy to just throw in the translated versions of some of these for different languages.

**Comment by EelkoL** [comment]
You are right that I use the Dutch locale. However, I tested changing that, changed the Windows language, region but also the system locale  and the Q button still does nothing. I tried also the Chrome plugin 'Locale Switchter', but nothing. Moved Dutch down in chrome://settings/languages but again, no result. 
Then I tried the local copy of the todoist-shortcuts plugin, but I don't know what I should change, maybe the quickAdd function?

**Comment by mgsloan** [comment]
Does the button in Todoist visually use Dutch?  I'd only expect the locale change to work if the button also visually changes to "Add task"

Yes it'd be in `quickAdd`, something like `(button) => button.innerText.includes('Voeg taak toe')`

**Comment by EelkoL** [comment]
Your Dutch is not bad at all. The button actually says 'Taak toevoegen'.

Your comment made me try something simple: Change the language in the Todoist settings (in General). That does the trick! 
My windows is still Dutch, the locale is set to The Netherlands, only Todoist is now in English. And the Q-key works again. 

Thanks a lot!
