### ISSUE TITLE
Action bar hidden when applying actions

### ISSUE THREAD

**Issue by amix** [mgsloan/todoist-shortcuts#32]
Steps to reproduce:
* Select multiple tasks
* Apply an action (e.g., `2` to change priority)

What I expect:
* That the top action bar will stay visible

What happens:
* Tasks are selected, but the top action bar gets hidden

**Comment by mgsloan** [comment]
Thanks for the report!  I actually had a workaround for this issue - https://github.com/mgsloan/todoist-shortcuts/commit/6938cb969084721d0c629a95855ad1895b560c77#diff-abbd4e09a53fc33643ce46f145654694L791 - but I removed it since I no longer saw the issue.  I didn't notice that this case still remained.

Rather than reinstating that hack, I've disabled attempting to restore selections after priority changes.  This particularly makes sense to me because priority changing actions were the only one with selection restoration - I had not yet applied it to move-to-project or reschedule.  Those are trickier since there are multiple steps to the interaction.

Perhaps Todoist's behavior could be changed here?  It seems useful to keep the selections after doing group actions.  This would require a good way to deselect all items with the mouse, and I'm not sure what that should be.  Perhaps clicking off to the sides of the editor / shift clicking there?

**Comment by amix** [comment]
Thanks for looking into this, @mgsloan 

> Perhaps Todoist's behavior could be changed here?

Yea, it's something we will need to think about. This said, from the stats we have most people only do one action to some items (it's not common to do the same action to the same items).

**Comment by mgsloan** [comment]
That makes sense!  Yeah I'm not sure if I ever need to do more than one action to some items either.  We'll see - I think for now it's best to have consistent behavior and so deselecting is fine.
