### ISSUE TITLE
Project, Label, and Filter Sections Not Collapsible In Section Navigation Mode

### ISSUE THREAD

**Issue by AndyHickman** [mgsloan/todoist-shortcuts#34]
See this recorded screencast demoing: https://www.dropbox.com/s/6kzw4lzns2c7f2s/section%20navigation%20issue.mp4?dl=0

Thank you for all your work - this whole thing is amazing!

-Andy

**Comment by mgsloan** [comment]
Good catch @AndyHickman .  This turned out to be a display issue, I think that Todoist updated some CSS that occluded the shortcut tip.  I have updated the CSS of todoist-shortcuts to always display tips above other elements.  I've released version 16 which resolves this issue among a few other changes.

I'm really glad you appreciate it.  While todoist-shortcuts is definitely scratching my own itch,  I wouldn't have put so much effort into this unless it was also useful to others :) 

Also, welcome to GitHub!
