### ISSUE TITLE
Are the Section Navigation Keystrokes Permanent for Favorites?

### ISSUE THREAD

**Issue by AndyHickman** [mgsloan/todoist-shortcuts#38]
I.e. will they have change based off of other projects that get created? Just like how I know g + i will ALWAYS land me in my inbox, is there a way to guarantee that certain key strokes will always land me in a favorited project, label, or filter?

(Sorry if this is techinically not an "issue." If there is a better place to post such a question, please direct me.)

**Comment by mgsloan** [comment]
There is a potential for them to change when adding more projects / labels / filters.  Since they are handled first, they are less likely to change than the others, but it can still happen.

You can add more stable sequences by cloning the code for the extension locally, and using an unpacked extension.  The list of stable sequences is here - https://github.com/mgsloan/todoist-shortcuts/blob/master/src/todoist-shortcuts.js#L2178 .  For now, all customization of this extension is by modifying the source code.  The main downside of this is that you'll need to remember to periodically pull in upstream changes.
