### ISSUE TITLE
'escape' doesn't exit Quick Add Task or Add label

### ISSUE THREAD

**Issue by brettmiller** [mgsloan/todoist-shortcuts#66]
After bring up "Quick Add Task" with 'q' or "Add label" with '@' hitting 'esc' to cancel the changes and close the dialog box no longer works. The only way to dismiss the dialog is with the mouse.

**Comment by mgsloan** [comment]
Hmm, curious!  At first I didn't see this problem.  Then I refreshed once, and saw it happen, but after switching projects the problem went away.  Subsequent refreshes didn't have the problem.  So, it seems to be some sporadic bug.

Handling of escape for that is done by Todoist.  It is conceivable that it could be due to an issue with todoist-shortcuts, since it does some keyboard event interception.  It seems unlikely to me that the behavior of this interception would vary sporadically, so I am thinking this is an upstream bug.

**Comment by brettmiller** [comment]
It was always broken for me. I'd also found it did't work with the comment dialog either. I removed and added the extension back and now things are working. 🤷‍♂️

**Comment by mgsloan** [comment]
One of the changelog notes in Todoist version 940 is

> 🐛The keyboard shortcuts for adding and editing a task were acting up but that's been fixed.

Perhaps that's related to this issue
