### ISSUE TITLE
Printable cheat sheet in Google Spreadsheets

### ISSUE THREAD

**Issue by kimaero** [mgsloan/todoist-shortcuts#71]
I've created a printable cheat sheet to make it easier to remember the keys. I suppose it could be useful for others, so you may want to include it in the description. 

https://docs.google.com/spreadsheets/d/1AGh85HlDze19bWpCa2OTErv9xc7grmMOMRV9S2OS7Xk/edit?usp=sharing

It would be nice though to have some overlay or a side window with the list of keys right in the todoist.

**Comment by mgsloan** [comment]
This looks awesome, great work!  Will certainly add a link to it.

I agree it would be nice to have an overlay, this is a good step in that direction.  One reason such an overlay doesn't exist is that the existing documentation wouldn't nicely fit in such an overlay.

Could you please add me as an editor of this sheet?  (mgsloan@gmail.com)  That way I can help keep it up to date if things change.

**Comment by kimaero** [comment]
Sure, done!

**Comment by greg-rowe** [comment]
Could you fit it in an overlay if the overlay were context sensitive? For example if currently editing a task only show the shortcuts that are possible?

**Comment by mgsloan** [comment]
I've added a link to the sheet, thanks again @kimaero !  I've also made it so that the `?` key brings up a modal, and released that as version 52.  Here's what it looks like:

![image](https://user-images.githubusercontent.com/22570/59557290-6e007900-8f93-11e9-9bbf-17f30c6951cf.png)

Would also be nice to have a settings menu item that opens the modal, but eh, I'm about done working on this for today - created a todo item I might get around to at some point.

**Comment by frankydee** [comment]
Hi,  I know this issue is closed but, I think it would really be worth mentioning the '?' shortcut in the documentation (readme.md) as it currently doesn't appear.  People will never find out about it unless they follow the link to this issue and read the comment history...   which probably very few do. 
Thanks

**Comment by mgsloan** [comment]
@frankydee Great point!  Version 60 documents `?` properly
