### ISSUE TITLE
Sort by Date no long work

### ISSUE THREAD

**Issue by h-chatha** [mgsloan/todoist-shortcuts#76]
Sort by Date keyboard shortcut no longer works. Please help.

**Comment by mgsloan** [comment]
Thanks for reporting this bug!  I don't use this feature much so I wouldn't have noticed.

For this keybinding, the extension was not handling the keypress since regular Todoist had a sort-by-date binding for `s`.  However, it looks like Todoist has changed the keybinding for sort-by-date to instead be `d`.

todoist-shortcuts is already using `d` for marking items complete, and that is very much so in the muscle memory of me and other users.  So, I've made a change so that `s` will once again cause sorting by date, and this has been released in version 54.

**Comment by h-chatha** [comment]
@mgsloan thank you very much. It works now. Btw, I love this extension and can't live without it.

**Comment by mgsloan** [comment]
Great!  I'm glad that you appreciate it so much :D
